version: '3'
services:
  web:
    build: 
      context: ./
      dockerfile: webdocker
    container_name: web
    ports: [8080:8080]
  server:
    build: 
      context: ./
      dockerfile: serverdocker
    container_name: server
    ports: [3000:3000]
